S00 us00 start
WildCodeSchool/orleans-php-202009-project-design-broderie pull request #1
Opened 2020-10-23 08:40 UTC by BarbaraGonthier

2020-10-23 08:56 UTC, ChenuetLoic approved these changes

2020-10-23 08:56 UTC, ChenuetLoic approved these changes

2020-10-23 08:56 UTC, ChenuetLoic approved these changes

2020-10-23 10:24 UTC, sblondeau requested changes

2020-10-23 10:24 UTC, sblondeau commented on src/View/layout.html.twig
> +        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" cros
bootstrap doit etre appelé AVANT le style.css, sinon tu ne pourras pas le surcharger (et avant le block stylesheet)

2020-10-23 10:24 UTC, sblondeau commented on src/View/layout.html.twig
> +            <header>
pas la peine de définir les balises header et nav là, ça sera dans la PR sur la navbar, et la navbar sera dans un autre fichier que tu vas include

2020-10-23 10:24 UTC, sblondeau commented on src/View/layout.html.twig
> +        {% block javascript %}{% endblock %}
le bloc javascript (qui contiendra ton code js eventuel) doit etre appelé également après les fichier js de bootstrap

2020-10-23 13:16 UTC, sblondeau requested changes

2020-10-23 13:16 UTC, sblondeau commented on src/View/layout.html.twig
> +        {% block stylesheet %}<link rel="stylesheet" href="/assets/css/style.css">
Je vous conseille de ne pasmettre la feuille de style principale style.css à l'intérieur du block stylesheet car ça va t'obliger à remettre {{parent()}} a chaque fois que tu voudras rajouter un CSS dans une autre page, ce qui me semble inutile.

2020-10-26 08:24 UTC, sblondeau approved these changes

2020-10-26 16:02 UTC, sblondeau approved these changes

2020-10-26 16:02 UTC, merged