S01 us01 banner
WildCodeSchool/orleans-php-202009-project-design-broderie pull request #20
Opened 2020-10-28 15:33 UTC by ChenuetLoic

2020-10-28 18:20 UTC, KevinVanphavong approved these changes

2020-10-29 08:59 UTC, sblondeau requested changes
pourquoi charge tu toutes ces images sur cette US ? Je ne pense pas que ce soit nécesaire.
De plus fais en sorte que les images pèsent le moins possible, fixe toi 100-200ko max, certaines sont plus grosses que ça donc il faut les réduire. 
(mais je pense que c'est plutot une autre US...)

2020-10-29 08:59 UTC, sblondeau commented on src/View/Home/_footer.html.twig
> +                    <h6 class="text-uppercase font-weight-bold">Liens utiles</h6>
pas de h6 si tu n'as pas de h5 avant, suit l'ordre hierarchique des titres (ici h2 j'ai l'impression)

2020-10-29 08:59 UTC, sblondeau commented on src/View/Home/_footer.html.twig
> +                    <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
pas de style en inline

2020-10-29 08:59 UTC, sblondeau commented on src/View/Home/_footer.html.twig
> +                    <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
style inline

2020-10-29 08:59 UTC, sblondeau commented on src/View/layout.html.twig
> +        {% block footer %}
je ne comprends pas ta US qui s'appelle Banner alors que c'est un footer ?

2020-10-29 15:24 UTC, KevinVanphavong approved these changes

2020-10-29 15:32 UTC, KevinVanphavong approved these changes

2020-10-29 15:49 UTC, sblondeau approved these changes

2020-10-29 15:49 UTC, merged