S01 us02 form 2
WildCodeSchool/orleans-php-202009-project-design-broderie pull request #21
Opened 2020-10-28 15:50 UTC by BarbaraGonthier

2020-10-28 17:50 UTC, KevinVanphavong approved these changes

2020-10-28 17:55 UTC, KevinVanphavong approved these changes

2020-10-29 08:46 UTC, sblondeau commented
ne passe pas travis

2020-10-29 10:54 UTC, sblondeau requested changes

2020-10-29 10:54 UTC, sblondeau commented on public/assets/css/form.css
> +@media screen and (max-width: 740px) {
media query sans doute inutile

2020-10-29 10:54 UTC, sblondeau commented on src/Controller/OrderController.php
> +                $orderManager->saveOrder($order, $product);
instancie le $orderManager ici et pas avant ta condition car tu n'en as besoin qu'à l'intérieur de celle-ci

2020-10-29 10:54 UTC, sblondeau commented on src/Controller/OrderController.php
> +            $errors[] = 'Le champ prénom doit contenir moins de 100 caractères';
utilise plutot une varable $inputLength = 100 que tu mets dans la comparaison et le message d'erreur pour etre sur de rester bien cohérent entre les deux

2020-10-29 13:00 UTC, BarbaraGonthier commented on public/assets/css/form.css
> +@media screen and (max-width: 740px) {
le texte est trop gros sans cette media queries du coup j'ai dû les laisser

2020-10-29 13:27 UTC, sblondeau requested changes

2020-10-29 13:27 UTC, sblondeau commented on src/Controller/OrderController.php
> +            $errors[] = 'Le champ prénom doit contenir moins de 100 caractères';
non l'idée c'est de mettre aussi dans le message d'erreur
             $errors[] = 'Le champ prénom doit contenir moins de ' . $inputLength . ' caractères'; 

et aussi une variable pour la longueur 20 plus bas :-)

2020-10-29 13:27 UTC, sblondeau commented on public/assets/css/form.css
> +@media screen and (max-width: 740px) {
dans ce cas il faut juste changer la variable et pas besoin du font-size sur le h1 et h2, ça devrait etre en dehors de la media query ça

2020-10-29 16:11 UTC, sblondeau approved these changes

2020-10-30 08:50 UTC, merged